### ISSUE TITLE
Commands fail when secret service is not installed

### ISSUE THREAD

**Issue by thinca** [kyoh86/gordon#19]
OS: Linux (without X)

In my environment, some commands fail with the following message.
I cannot install/update any packages.

```
% gordon update --all
error: The name org.freedesktop.secrets was not provided by any .service files
```

version
```
% gordon --version
0.1.8-22eb850ae5608fcc46171b7a38deaa9fd84c4a05 (2020-07-24T15:18:12Z)
```

**Comment by kyoh86** [comment]
@thinca this may be fixed.

**Comment by thinca** [comment]
I re-installed latest `gordon` and install some commands, then `gordon update --all` was silently succeeded!  Maybe this has been fixed. Thanks!
