### ISSUE TITLE
Cannot install client9/misspell on macOS

### ISSUE THREAD

**Issue by thinca** [kyoh86/gordon#20]
OS: macOS Catalina 10.15.6

https://github.com/client9/misspell/releases/tag/v0.3.4

```
% gordon install client9/misspell@v0.3.4
error: asset not found
```

(v0.3.4 is latest version at now.  It can be reproduced without `@v0.3.4`.)

**Comment by kyoh86** [comment]
gordon searches an asset from a release which has a name matching your `OS` and `Architecture` information.
Using macOS Catalina, it uses "osx", "mac" or the "macintosh" as the `OS` and "amd64" as the `Architecture`.
But now, client9/misspell@v0.3.4 has no asset matching the architecture.
i.e. `misspell_0.3.4_mac_64bit.tar.gz` does not contain "amd64".

To hack it, `GORDON_ARCHITECTURE=64bit gordon install client9/misspell@v0.3.4` will find that asset and install it.
But it will not be able to be updated with `gordon update`...

:thought_balloon: I should fix the gordon to fallback well to another asset if all of asset are not matched for the conditions.
